Aprender/urls.py
from django.contrib import admin
from django.urls import path, include

 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include(('Aprendo.urls', 'Aprendo'), namespace='Aprendo')),
]

Aprendo/urls.py
"""Define los patrones para urls de aprendo."""

from django.urls import path, include
from . import views


urlpatterns = [
    # home page 
    path('',views.index, name='index'),
    #pagina que muestra los topics.
    path('topics/', views.topics, name='topics'),
    #pagina detallada para un solo topico
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    #pagina para adjuntar nuevos topicos temas 
    path('new_topic/', views.new_topic, name='new_topic'),
    #pagina para adjuntar nuevas entradas 
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    #pagina para editar un entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
""" Definimos los patrones urls para users"""

from atexit import register
from django.urls import path, include


from .import views

app_name = 'users'
urlpatterns = [
   # incluye auth urls por defecto
    path('', include('django.contrib.auth.urls')), 
    # pagina de registro
    path('register/', views.register, name='register'), 
]

 

Aprendo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # muy importante sin este def no se ven los titulos de los topics
    def __str__(self):
        return self.text

class Entry(models.Model):
    """algo especifico aprendido acerca del tema"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        """Retorna un string representacion del modelo"""
        return f"{self.text[:50]}..."
        #return self.text[:50]+'...'

users/models.py
from django.db import models

# Create your models here.

Aprendo/forms.py
from django import forms 

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}
        

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':'Entry'}
        Widgets = {'text': forms.Textarea(attrs={'cols':80})}

Aprendo/views.py
import http
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """Home page para Aprendo."""
    return render(request, 'Aprendo/index.html' )

@login_required    
def topics(request):
    """muestra todos los topicos"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request, 'Aprendo/topics.html', context)

@login_required  
def topic(request, topic_id):
    """muestra un topico con todas sus entradas"""
    topic = Topic.objects.get(id=topic_id)
    #asegurandose que el topico pertenece a su usuario correspondiente.
    if topic.owner != request.user:
        raise Http404
    
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'Aprendo/topic.html', context)

@login_required  
def new_topic(request):
    """agregar un nuevo tema"""
    if request.method != 'POST':
        # No hay datos suministrados crear una forma en blanco.
        form = TopicForm()
    else:
        # POST datos suministrados procesar datos.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('Aprendo:topics')
    
    #Desplega una forma en blanco
    context = {'form': form}
    return render(request, 'Aprendo/new_topic.html', context)

@login_required  
def new_entry(request, topic_id):
    """agregar un nuevo tema a un topic en particular"""
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        # No hay datos suministrados crear una forma en blanco.
        form = EntryForm()
    else:
        # POST datos suministrados procesar datos.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('Aprendo:topic', topic_id=topic_id)
    
    #Desplega una forma en blanco
    context = {'topic':topic,'form': form}
    return render(request, 'Aprendo/new_entry.html', context)

@login_required  
def edit_entry(request, entry_id):
    """Editar una entrada existente"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        # requerimiento inicial prellenado de la forma con la entrada actual  
        form = EntryForm(instance=entry)
    else:
        # POST datos suministrados procesar datos.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('Aprendo:topic', topic_id=topic.id)
    
    context = {'entry':entry ,'topic':topic,'form': form}
    return render(request, 'Aprendo/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    """registrar un nuevo usuario"""  
    if request.method != 'POST':
        # muestra forma de registro en blanco
        form = UserCreationForm()
    else:
        # procesar forma completada.
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # accesando en usuario dentro y redirigir al home page
            login(request, new_user)
            return redirect('Aprendo:index')
    
    context = {'form': form}
    return render(request, 'registration/register.html', context)

def logout_request(request): #agregado 3/10/22
    return redirect(request,'users:logout')
    

Aprendo/templates/Aprendo/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Aprendo Esto!</title>

  {% bootstrap_css %} 
  {% bootstrap_javascript jquery='full' %}   
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'Aprendo:index' %}">APRENDO ESTO</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'Aprendo:topics' %}">Topics</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto"
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text"}"> Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href ="{% url 'users:logout' %}">Log out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>    
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a> 
            {% endif %}
            </ul>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content  %}
        </div>
    </main>

</body>

</html>

Aprendo/templates/Aprendo/edit_entry.html
{% extends "Aprendo/base.html" %}

{% block content %}

    <p><a href="{% url 'Aprendo:topic' topic.id %}">{{ topic }}</a></p>

    <p>Edit entry:</p>
    <form action="{% url 'Aprendo:edit_entry' entry.id %}" method='post'>
     {% csrf_token %}
     {{ form.as_p }}
     <button name="submit">Save changes</button>
    </form>

{% endblock content %}

Aprendo/templates/Aprendo/index.html
{% extends 'Aprendo/base.html' %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Seguimiento a su aprendizaje</h1>
                
        <p class="lead">Haga su propio seguimiento a su aprendizaje, mantenga una lista de los temas que esta aprendiendo.
                Cuando aprenda algo nuevo acerca de un tema haga una nueva entrada resumiendo lo que aprendio</p>
        <a class="btn btn-outline-center-primary" type="button" href="{% url 'users:register' %}"role="button">Register</a>
    </div>
{% endblock %}

Aprendo/templates/Aprendo/new_entry.html
{% extends "Aprendo/base.html" %}

{% block content %}

    <p><a href="{% url 'Aprendo:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry:</p>
    <form action="{% url 'Aprendo:new_entry' topic.id %}" method='post'>
     {% csrf_token %}
     {{ form.as_p }}
     <button name="submit">Add entry</button>
    </form>

{% endblock content %}

Aprendo/templates/Aprendo/new_topic.html
{% extends "Aprendo/base.html" %}

{% block content %}
    <p>Add a new topic:</p>

    <form action="{% url 'Aprendo:new_topic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add topic</button>
    </form>

{% endblock content %}

Aprendo/templates/Aprendo/topic.html
{% extends "Aprendo/base.html" %}

{% block page_header %}
    <h1>{{ Topic }}</h1>
{% endblock page_header %}

{% block content %}
    <p>
      <a href="{% url 'Aprendo:new_entry' topic.id %}">Agrege una nueva entrada</a>
    </p>
    
    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
            {{ entry.date_added|date:'M d, Y H:i' }}
            <small><a href="{% url 'Aprendo:edit_entry' entry.id %}">Editar Entrada</a></small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>No hay entradas todavia.</p>
    {% endfor %}
    
{% endblock content %}

Aprendo/templates/Aprendo/topics.html
{% extends "Aprendo/base.html" %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li><h3>
             <a href="{% url 'Aprendo:topic' topic.id %}">{{ topic }}</a>
            </h3></li>
        {% empty %}
            <li><h3>No se an agregado temas todavia.</h3></li>
        {% endfor %}
    </ul>

    <h3><a href="{% url 'Aprendo:new_topic' %}">Agregar un nuevo tema</a></h3>

{% endblock content %}